# Configuration overrides during development

[peer]
id = "defe10bb-a12a-4ad9-b18e-8149099dd044"

[network]
connect.interval.ms = 250

[network.tls]
ca = "resources/development/tls/insecure-development-ca.pem"
domain.name.override = "localhost"

[network.interface.management]
enabled = false

[vpn]
enabled = false

[vpn.disabled]
remote.host = "127.0.0.1"

[opentelemetry]
enabled = true
endpoint = "http://localhost:4317"