[peer]
id = ""

[network]
carl.host = "localhost"
carl.port = 8080
connect.retries = 10
connect.interval.ms = 5000

[network.tls]
ca.certificate = "/etc/opendut-network/tls/ca.pem"
domain.name.override = ""

[network.interface.management]
enabled = true

[vpn]
enabled = true

[vpn.disabled]
remote.host = ""