[carl]
disconnect.timeout.ms = 30000

[peer]
id = ""

[network]
carl.host = "localhost"
carl.port = 8080
connect.retries = 10
connect.interval.ms = 5000

[network.tls]
ca = "/etc/opendut/tls/ca.pem"
domain.name.override = ""

[network.oidc]
enabled = false

[network.oidc.client]
id = "opendut-edgar-client"
issuer.url = "https://keycloak/realms/opendut/"
scopes = "openid,profile,email"
secret = "<tbd>"


[network.interface.management]
enabled = true

[vpn]
enabled = true

[vpn.disabled]
remote.host = ""

[logging]
stdout = true

[opentelemetry]
enabled = false
collector.endpoint = ""
service.name = "opendut-edgar"

[opentelemetry.metrics]
interval.ms = 60000
cpu.collection.interval.ms = 5000

[opentelemetry.metrics.cluster]
ping.interval.ms = 30000
target.bandwidth.kilobit.per.second = 100_000
rperf.backoff.max.elapsed.time.ms = 120000
