[package]
name = "opendut-theo"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
opendut-util = { workspace = true }

clap = { workspace = true, features = ["derive", "wrap_help", "env"] }
dotenvy = { workspace = true }
phf = { workspace = true, features = ["macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
sudo = { workspace = true }
thiserror = { workspace = true }
cargo_toml = { workspace = true }
ctrlc = { workspace = true }
home = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true }
