[package]
name = "opendut-util-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
dotenvy = { workspace = true, optional = true }

ring = { workspace = true } #workaround for: https://github.com/briansmith/ring/issues/2454

[features]
default = []
testing = ["dotenvy"]

[lints]
workspace = true
