[package]
name = "opendut-util-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
config = { workspace = true, optional = true }
dotenvy = { workspace = true, optional = true }
pem = { workspace = true }
reqwest = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = ["settings"]
settings = ["dep:config"]
reqwest = ["dep:reqwest", "settings"]
testing = ["dotenvy"]

[lints]
workspace = true
