[package]
name = "opendut-util-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
config = { workspace = true, optional = true }
dotenvy = { workspace = true, optional = true }
pem = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
reqwest = ["pem", "dep:reqwest"]
pem = ["dep:config", "dep:pem"]
testing = ["dotenvy"]

[lints]
workspace = true
