- name: Update /etc/hosts
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      192.168.56.10 opendut.local
      192.168.56.10 auth.opendut.local
      192.168.56.10 netbird.opendut.local
      192.168.56.10 netbird-api.opendut.local
      192.168.56.10 signal.opendut.local
      192.168.56.10 carl.opendut.local
      192.168.56.10 nginx-webdav.opendut.local
      192.168.56.10 opentelemetry.opendut.local
      192.168.56.10 monitoring.opendut.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK of services"

- name: Copy insecure development certificate authority
  become: true
  copy:
    src: "{{ opendut_repo_root }}/resources/development/tls/insecure-development-ca.pem"
    dest: /usr/local/share/ca-certificates/insecure-development-ca.crt  # *.crt suffix required
  register: development_ca_copy_task

- name: Add custom certificate authority
  copy:
    src: "{{ custom_root_ca_path }}"
    dest: /usr/local/share/ca-certificates/custom_root_ca.crt
    mode: 0644
  when: custom_root_ca_path is defined
  register: custom_root_ca_task

- name: Update ca certificates
  become: true
  shell: "update-ca-certificates"
  when: development_ca_copy_task.changed or custom_root_ca_task.changed

- name: Create custom cargo target directory
  file:
    path: /home/vagrant/rust-target
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Ensure cargo target directory is overridden in virtual machine
  become: true
  become_user: vagrant
  ansible.builtin.lineinfile:
    path: /home/vagrant/.bashrc
    regexp: '^export CARGO_TARGET_DIR='
    line: "export CARGO_TARGET_DIR=/home/vagrant/rust-target"

- name: Include rust-target debug directory in PATH
  become: true
  become_user: vagrant
  ansible.builtin.lineinfile:
    path: /home/vagrant/.bashrc
    regexp: '^export PATH='
    line: "export PATH=/home/vagrant/rust-target/debug/:$PATH"

- import_tasks: custom_ntp.yml
