[package]
name = "opendut-viper-containers"
description = "Library for executing containers as part of VIPER."
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
docker = ["dep:bollard"]
mock = []

[dependencies]
async-trait = { workspace = true }
bollard = { workspace = true, optional = true, default-features = true }
futures = { workspace = true }

[dev-dependencies]
googletest = { workspace = true }
