[package]
name = "viper-pygen-example"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
viper-pygen = { workspace = true }
indoc = { workspace = true }
