[package]
name = "opendut-viper-pygen-example"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
opendut-viper-pygen = { workspace = true }
indoc = { workspace = true }
