[package]
name = "opendut-viper-pygen-example"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
opendut-viper-pygen = { workspace = true }
indoc = { workspace = true }
