- name: Set apply_dir fact
  set_fact:
    apply_file: "{{ ansible_host }}.yaml"
    apply_dir: "/tmp/opendut/cleo/apply"

- name: Create temp dir for CLEO apply config
  file:
    path: "{{ apply_dir }}"
    state: directory

- name: Upload to backend
  copy:
    src: "{{ inventory_dir }}/{{ cleo_apply_dir }}/{{ apply_file }}"
    dest: "{{ apply_dir }}"

- name: Upload into CLEO container
  command: "docker cp {{ apply_dir }}/{{ apply_file }} opendut-cleo:/tmp/{{ apply_file }}"

- name: Apply peer/cluster configuration to CARL
  command: "docker exec opendut-cleo opendut-cleo apply /tmp/{{ apply_file }}"
