services:
  nginx-webdav:
    build:
      context: ../../..
      dockerfile: ./.ci/docker/nginx-webdav/Dockerfile
    container_name: nginx-webdav

    volumes:
      - opendut_nginx-webdav:/media/data
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      - logging=alloy
      - logging_job=nginx-webdav
    networks:
      - opendutnet

networks:
  opendutnet:
    name: opendut_network
    external: true  # Use a pre-existing network

volumes:
  opendut_nginx-webdav:
