argument_specs:
  main:
    description:
      - Set up a proxy server on the Ansible Controller to give internet access to edge devices during playbook execution.
      - This assumes that we're connected to the Raspberry Pi via a WiFi hotspot that the Raspberry Pi broadcasts. In NetworkManager's default configuration, it should give us an IP address of 10.42.0.x.
    options:
      ansible_proxy_server_state:
        description: "Whether to install the role or remove it."
        type: "str"
        choices:
          - "present"
          - "absent"
        required: false

      ansible_proxy_server_port:
        description: "The network port to run the server on."
        type: "int"
        required: false
