---
# See also https://github.com/linuxserver/docker-firefox?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info

services:
  firefox:
    container_name: opendut-firefox
    build:
      context: ../../../..
      dockerfile: ./.ci/deploy/testenv/firefox/Dockerfile
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TITLE=OpenDuT-Browser

    volumes:
      - opendut_firefox-profile:/config
      - opendut_provision-secrets-data:/provision:ro
    shm_size: "1gb"
    #restart: unless-stopped
    networks:
      - opendut_local

volumes:
  opendut_firefox-profile:
  opendut_provision-secrets-data:
    external: true

networks:
  opendut_local:
    name: opendut_local
    external: true  # Use a pre-existing network
