[package]
name = "opendut-viper-pygen"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
indoc = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "visit-mut"] }

[dev-dependencies]
trybuild = { workspace = true }
rustpython-vm = { workspace = true }
