[package]
name = "opendut-viper-pygen"
description = "Library for generating Python stubs to support auto-completiong in VIPER."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
indoc = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "visit-mut"] }

[dev-dependencies]
trybuild = { workspace = true }
rustpython-vm = { workspace = true }
