#!/usr/bin/env ansible-playbook
---
- name: Create Peer configuration in CARL
  hosts: backend
  gather_facts: false
  vars:
    apply_file: "{{ inventory_dir }}/{{ ansible_host }}.yaml"
  tasks:
    - name: Include cleo-apply playbook
      include_tasks: "tasks/edge/cleo_apply.yaml"
      when: apply_file is exists


- name: Create /etc/hosts entry for backend
  hosts: edge
  gather_facts: false
  tasks:
    - name: Determine Backend IP
      set_fact:
        backend_ip: "{{ hostvars[backend]['ip_for_edge_hosts_file'] }}"

    - name: Write /etc/hosts entry
      blockinfile:
        path: /etc/hosts
        block: |
          # {{ backend }}
          {{ backend_ip }} opendut.local
          {{ backend_ip }} auth.opendut.local
          {{ backend_ip }} netbird.opendut.local
          {{ backend_ip }} netbird-api.opendut.local
          {{ backend_ip }} signal.opendut.local
          {{ backend_ip }} carl.opendut.local
          {{ backend_ip }} nginx-webdav.opendut.local
          {{ backend_ip }} opentelemetry.opendut.local
          {{ backend_ip }} monitoring.opendut.local


- name: Fetch CARL certificate for EDGAR download
  hosts: edge
  gather_facts: false
  vars:
    ca_cert_dir: "/tmp/opendut/"
    ca_cert_download: "/tmp/opendut/{{ backend }}.pem"
  tasks:
    - name: Fetch certificate from CARL
      delegate_to: "{{ backend }}"
      fetch:
        src: "{{ hostvars[backend]['repo_dir'] }}/.ci/deploy/localenv/data/secrets/pki/opendut-ca.pem"
        dest: "{{ ca_cert_download }}"
        flat: true

    - name: Set ca_cert fact
      set_fact:
        ca_cert: "/tmp/opendut/opendut-ca.crt"

    - name: Create ca_cert_dir
      file:
        path: "{{ ca_cert_dir }}"
        state: directory

    - name: Push certificate to edge host
      copy:
        src: "{{ ca_cert_download }}"
        dest: "{{ ca_cert }}"


- name: Download EDGAR from CARL
  hosts: edge
  gather_facts: false
  vars:
    arch_map:
      x86_64: "x86_64-unknown-linux-gnu"
      armv7l: "armv7-unknown-linux-gnueabihf"
      aarch64: "aarch64-unknown-linux-gnu"
    edgar_download: "/tmp/opendut/edgar.tar.gz"
  tasks:
    - name: Determine current date on ansible controller, assumes that it has a more accurate time than the edge hosts
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_delegation.html
      # delegate_to: "localhost"  # expects 'ssh localhost' to work
      local_action:
        module: command
        cmd: "date --rfc-3339=seconds"
      register: _date_output
      changed_when: false

    - name: Set current date
      command: "date --set='{{ _date_output.stdout }}'"

    - name: Determine CPU architecture
      command: "uname --machine"
      register: _uname_output
      changed_when: false

    - name: Set cpu_arch fact
      set_fact:
        cpu_arch: "{{ _uname_output.stdout }}"

    - name: Download EDGAR archive
      get_url:
        url: "https://carl.opendut.local/api/edgar/{{ arch_map[cpu_arch] }}/download"
        dest: "{{ edgar_download }}"
      environment:
        SSL_CERT_FILE: "{{ ca_cert }}"

    - name: Set edgar_unpack_dir fact
      set_fact:
        edgar_unpack_dir: "/tmp/opendut/edgar/"

    - name: Create EDGAR unpack dir
      file:
        path: "{{ edgar_unpack_dir }}"
        state: "directory"

    - name: Unpack EDGAR archive
      unarchive:
        src: "{{ edgar_download }}"
        remote_src: true
        dest: "{{ edgar_unpack_dir }}"


- name: Install Cannelloni
  hosts: edge
  gather_facts: false
  vars:
    arch_map:
      x86_64: "manylinux_2_28-x64"
      armv7l: "linux-armv6-lts" # "armv7" build of Cannelloni does not work on all Raspberry Pis reporting "armv7l"
      aarch64: "linux-arm64-lts"
    cannelloni_dir: "/tmp/opendut/"
  tasks:
    - name: Check if EDGAR service exists
      stat: path=/etc/systemd/system/opendut-edgar.service
      register: edgar_service_status

    - name: Stop EDGAR to allow replacing Cannelloni executable
      systemd_service:
        name: opendut-edgar
        state: stopped
      when: edgar_service_status.stat.exists

    - name: Install can-utils
      apt:
        name: "can-utils"
        state: present

    - name: Download and unpack Cannelloni
      unarchive:
        src: "https://github.com/eclipse-opendut/cannelloni-build/releases/download/v1.1.0/cannelloni_{{ arch_map[cpu_arch] }}_1.1.0.tar.gz"
        remote_src: true
        dest: "{{ cannelloni_dir }}"

    - name: Copy Cannelloni into OS PATH
      shell:
        cmd: |
          cp libcannelloni-common.so.0 /lib/
          cp libsctp.so* /lib/
          cp cannelloni /usr/local/bin/
        chdir: "{{ cannelloni_dir }}/cannelloni/"


- name: Retrieve Setup-String from CARL
  hosts: edge
  gather_facts: false
  tasks:
    - name: Retrieve Setup-String from CARL
      delegate_to: "{{ backend }}"
      command:
        cmd: "docker exec opendut-cleo opendut-cleo generate-setup-string {{ peer_id }}"
      register: _setup_string_output

    - name: Store Setup-String
      set_fact:
        setup_string: "{{ _setup_string_output.stdout }}"


- name: Setup EDGARs
  hosts: edge
  gather_facts: false
  vars:
    config_dir: "/etc/opendut/"
    config_file: "{{ config_dir }}/edgar.toml"
  tasks:
    - name: Create EDGAR config directory
      file:
        path: "{{ config_dir }}"
        state: directory

    - name: Write telemetry presets into EDGAR configuration file
      copy:
        dest: "{{ config_file }}"
        mode: "0640"
        content: |
          [opentelemetry]
          enabled = true
          collector.endpoint = "https://opentelemetry.opendut.local"
          service.name = "opendut-edgar-{{ ansible_host }}"
      when: config_file is not exists

    - name: Run EDGAR Setup
      command:
        cmd: "opendut-edgar/opendut-edgar setup --no-confirm managed {{ setup_string }}"
        chdir: "{{ edgar_unpack_dir }}"
      environment:
        OPENDUT_EDGAR_SERVICE_USER: root
