[package]
name = "opendut-theo"
description = "Test Harness Environment Operator for OpenDUT"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["linux-kernel-modules"]
linux-kernel-modules = ["opendut-edgar-kernel-modules"]

[dependencies]
opendut-edgar-kernel-modules = { workspace = true, optional = true }

anyhow = { workspace = true }
cargo_toml = { workspace = true }
clap = { workspace = true, features = ["derive", "wrap_help", "env"] }
ctrlc = { workspace = true }
dotenvy = { workspace = true }
home = { workspace = true }
phf = { workspace = true, features = ["macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shadow-rs = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "ansi", "tracing-log"] }

[build-dependencies]
shadow-rs = { workspace = true, default-features = true }
