[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[alias]
ci = "run --package opendut-ci --"
cleo = "ci cleo run --"
carl = "ci carl run --"
edgar = "ci edgar run --"
lea = "ci lea run --"
theo = "ci theo run --"

carl-viper = "ci carl run --features=viper --"
lea-viper = "ci lea run --features=viper --"
