[build]
target = "index.html"

[watch]
watch = [
    "src",
    "assets",
    "../opendut-carl/opendut-carl-api",
    "../opendut-model",
    "opendut-lea-components"
]

[serve]
addresses = ["0.0.0.0"]
port = 8000
