ansible_proxy_server_state: "present"

ansible_proxy_server_controller_proxy_dir: "/tmp/opendut/ansible-px-proxy/"
ansible_proxy_server_controller_proxy_executable: "{{ ansible_proxy_server_controller_proxy_dir }}px"

ansible_proxy_server_pxproxy_version: "v0.10.2"
ansible_proxy_server_pxproxy_target: "linux-glibc-x86_64"

ansible_proxy_server_controller_pxproxy_config_file: "/tmp/opendut/px-proxy.ini"

ansible_proxy_server_port: 3127
ansible_proxy_server_forward_to_proxy: ""
ansible_proxy_server_forward_to_proxy_formatted: ""
