# Traefik forward configuration when localenv is running in docker on the host
[tcp.routers]
  [tcp.routers.router1]
    service = "carl"
    rule = "HostSNI(`*`)"
    [tcp.routers.router1.tls]
    passthrough = true

[tcp.services]
  [tcp.services.carl]
    [tcp.services.carl.loadBalancer]
    [[tcp.services.carl.loadBalancer.servers]]
    address = "192.168.32.1:8080"

[[tls.certificates]]
    certFile = "/provision/pki/deploy/carl.opendut.local.pem"
    keyFile = "/provision/pki/deploy/carl.opendut.local.key"
    stores = ["default"]
