[package]
name = "opendut-auth-tests"
description = "opendut auth integration tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
opendut-auth = { workspace = true, features = ["registration_client"] }
opendut-util-core = { workspace = true }
opendut-types = { workspace = true }

anyhow = { workspace = true }
rstest = { workspace = true }
googletest = { workspace = true }
pem = { workspace = true, features = ["serde"]}
url = { workspace = true }
openidconnect = { workspace = true, default-features = false, features = ["reqwest"] }
oauth2 = { workspace = true, default-features = false, features = ["reqwest"] }
http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
