# https://github.com/compose-spec/compose-spec/blob/master/spec.md#extension
x-common-healthcheck-params: &common-healthcheck-params
  interval: 1m
  timeout: 10s
  retries: 3
  start_period: 2m  # Probe failure during start will not be counted towards the maximum number of retries
  start_interval: 5s

services:
  keycloak_postgres:
    image: "postgres:14.4"
    restart: unless-stopped
    healthcheck:
      <<: *common-healthcheck-params
      test: [ "CMD", "pg_isready", "--quiet", "--dbname=postgres", "--username=postgres" ]
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$KEYCLOAK_POSTGRES_PASSWORD
      - POSTGRES_DB=keycloak
      - POSTGRES_HOST=postgres
    networks:
      - opendut_local

  keycloak:
    build:
      context: ../../..
      dockerfile: ./.ci/deploy/localenv/data/keycloak/Dockerfile-keycloak-server
      args:
        KEYCLOAK_VERSION: 22.0.2
    command: ['start', '--optimized']
    restart: unless-stopped
    depends_on:
      - keycloak_postgres
      - traefik
    # this healthcheck requires the init container for provisioning
    healthcheck:
      <<: *common-healthcheck-params
      test: [ "CMD", "curl", "-sf", "http://localhost:8080/realms/provisioning-done", "--output", "/dev/null" ]
    environment:
    - JAVA_OPTS_APPEND=-Dkeycloak.profile.feature.upload_scripts=enabled
    - KC_DB_PASSWORD=$KEYCLOAK_POSTGRES_PASSWORD
    - KC_DB_URL=jdbc:postgresql://keycloak_postgres/keycloak
    - KC_DB_USERNAME=postgres
    - KC_HEALTH_ENABLED=true
    - KC_HTTP_ENABLED=true
    - KC_METRICS_ENABLED=true
    - KC_HOSTNAME=auth.opendut.local
    - KC_PROXY=edge # reencrypt
    - KC_PROXY_ADDRESS_FORWARDING=true
    - KC_HOSTNAME_STRICT=false
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD
    labels:
      - "traefik.http.routers.keycloak.rule=Host(`auth.opendut.local`)"
      - "traefik.http.routers.keycloak.tls=true"
    networks:
      - opendut_local

  init_keycloak:
    build:
      context: ../../..
      dockerfile: .ci/deploy/localenv/data/keycloak/Dockerfile-keycloak-provision
      args:
        KEYCLOAK_VERSION: 22.0.2
    depends_on:
      keycloak:
        condition: service_started
    # uncomment this to stop container after provisioning is done
    command: [ "sleep" ]
    # for fast update of provisioning the scripts are mounted as volumes
    volumes:
      - ./../../docker/keycloak/keycloak_functions.sh:/keycloak_functions.sh
      - ./data/keycloak/provision.sh:/provision.sh
    environment:
      - KCADM_PATH=/opt/keycloak/bin/kcadm.sh
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD
      - NETBIRD_MANAGEMENT_CLIENT_SECRET
      - OPENDUT_CARL_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_EDGAR_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_USER_OPENDUT
      - NETBIRD_PASSWORD
    networks:
      opendut_local:

  # frontend
  traefik:
    image: docker.io/traefik:v2.10.4
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --ping=true
      # Redirect to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--log.level=DEBUG"
      - "--accesslog"
    environment:
      - "LEGO_CA_CERTIFICATES=/pki/insecure-development-ca.pem"
    ports:
      - "127.0.0.1:8080:8080"
      - "80:80"
      - "443:443"
    healthcheck:
      <<: *common-healthcheck-params
      test: ["CMD", "traefik", "healthcheck", "--ping"]
    volumes:
      - ./data/traefik/config:/etc/traefik/dynamic:ro
      - ./data/secrets/pki/:/pki
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      opendut_local:
        aliases:
          - opendut.local
          - netbird.opendut.local
          - netbird-api.opendut.local
          - auth.opendut.local
          - signal.opendut.local

# vaguely derived from: https://github.com/netbirdio/netbird/blob/main/infrastructure_files/docker-compose.yml.tmpl.traefik
  netbird-dashboard:
    image: netbirdio/dashboard:v2.5.0
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
      keycloak:
        condition: service_healthy
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://netbird-api.opendut.local
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://netbird-api.opendut.local
      # OIDC
      - AUTH_AUDIENCE=netbird-client
      - AUTH_CLIENT_ID=netbird-client
      - AUTH_CLIENT_SECRET=
      - AUTH_AUTHORITY=https://auth.opendut.local/realms/netbird
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - AUTH_REDIRECT_URI=
      - AUTH_SILENT_REDIRECT_URI=
    healthcheck:
      <<: *common-healthcheck-params
      test: ["CMD-SHELL", "curl --silent --output /dev/null -w '%{http_code}' http://localhost || exit 1"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-dashboard.rule=Host(`netbird.opendut.local`)
      - traefik.http.routers.netbird-dashboard.tls=true
      - traefik.http.services.netbird-dashboard.loadbalancer.server.port=80

    networks:
      - opendut_local

  # Signal
  netbird-signal:
    image: netbirdio/signal:0.28.9
    restart: unless-stopped
    volumes:
      - netbird-signal:/var/lib/netbird
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-signal.rule=Host(`signal.opendut.local`)
      - traefik.http.services.netbird-signal.loadbalancer.server.port=80
      - traefik.http.services.netbird-signal.loadbalancer.server.scheme=h2c
    networks:
      - opendut_local

  # Management
  netbird-management:
    build:
      context: ../../..
      dockerfile: ./.ci/deploy/localenv/data/netbird/Dockerfile_management
      args:
        NETBIRD_MANAGEMENT_VERSION: "0.28.9"
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
      netbird-dashboard:
        condition: service_started
      keycloak:
        condition: service_healthy
    volumes:
      - ./data/secrets/pki/:/pki/:ro
      - ./data/secrets/pki/insecure-development-ca.pem:/usr/local/share/ca-certificates/insecure-development-ca.crt:ro
      - ./data/netbird/config/:/config/:ro
      - netbird-mgmt-data:/var/lib/netbird
      - netbird-mgmt-config:/etc/netbird/
    environment:
      # Keycloak user
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD
      # CURL
      - CURL_CA_BUNDLE=/usr/local/share/ca-certificates/insecure-development-ca.crt
      # Netbird management is GO, GO uses SSL_CERT_FILE environment variable, see https://go.dev/src/crypto/x509/root_unix.go
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/insecure-development-ca.crt
      - KEYCLOAK_URL=https://auth.opendut.local
      - NETBIRD_MANAGEMENT_URL=https://netbird-api.opendut.local
      - NETBIRD_MANAGEMENT_DOMAIN=netbird.opendut.local
      - KEYCLOAK_REALM_URL=https://auth.opendut.local/realms/netbird/.well-known/openid-configuration
      # URLs
      - NETBIRD_SIGNAL_STUN_URL=signal.opendut.local:443
      - NETBIRD_SIGNAL_DOMAIN=signal.opendut.local
      - NETBIRD_SIGNAL_PROTOCOL=http
      - NETBIRD_SIGNAL_PORT=443
      - TURN_DOMAIN=opendut.local
      - TURN_USER=self
      - TURN_PASSWORD
      - TURN_PORT=3478
      - NETBIRD_DATASTORE_ENC_KEY
      - NETBIRD_ISSUER_URL=https://auth.opendut.local/realms/netbird
      - NETBIRD_ISSUER_DOMAIN=auth.opendut.local
      - NETBIRD_ISSUER_ADMIN_URL=https://auth.opendut.local/admin/realms/netbird
      - NETBIRD_MANAGEMENT_CLIENT_ID=netbird-backend
      - NETBIRD_MANAGEMENT_CLIENT_SECRET
      - NETBIRD_MANAGEMENT_DEVICE_ID=netbird-client
      - NETBIRD_PASSWORD

    healthcheck:
      <<: *common-healthcheck-params
      test: ["CMD-SHELL", "/netbird-management-health.sh"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-api.rule=Host(`netbird-api.opendut.local`) && PathPrefix(`/api`)
      - traefik.http.routers.netbird-api.service=netbird-api
      - traefik.http.routers.netbird-api.tls=true
      - traefik.http.services.netbird-api.loadbalancer.server.port=80

      - traefik.http.routers.netbird-management.rule=Host(`netbird-api.opendut.local`) && PathPrefix(`/management.ManagementService/`)
      - traefik.http.routers.netbird-management.service=netbird-management
      - traefik.http.routers.netbird-management.tls=true
      - traefik.http.services.netbird-management.loadbalancer.server.port=80
      - traefik.http.services.netbird-management.loadbalancer.server.scheme=h2c
    networks:
      - opendut_local

  # Coturn
  coturn:
    # https://hub.docker.com/r/coturn/coturn/tags
    # https://github.com/coturn/coturn/tree/master/docker/coturn#why-so-many-ports-opened
    image: coturn/coturn:4.6.2
    restart: unless-stopped
    domainname: opendut.local
    volumes:
      - ./data/coturn/:/coturn/:ro
    environment:
      - TURN_REALM=opendut.local
      - TURN_DOMAIN=opendut.local
      - TURN_USER=self
      - TURN_PASSWORD
      - TURN_PORT=3478
    network_mode: host  # only container using network host mode
    entrypoint: ["/coturn/entrypoint.sh"]
    # turnutils_uclient -T -p $TURN_PORT -u $TURN_USER -w $TURN_PASSWORD localhost
    healthcheck:
      <<: *common-healthcheck-params
      test: ["CMD-SHELL", "turnutils_uclient -T -p $$TURN_PORT -u $$TURN_USER -w $$TURN_PASSWORD localhost"]

  carl_postgres:
    image: "postgres:14.4"
    restart: unless-stopped
    healthcheck:
      <<: *common-healthcheck-params
      test: [ "CMD", "pg_isready", "--quiet", "--dbname=carl", "--username=postgres" ]
    volumes:
      - carl_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$CARL_POSTGRES_PASSWORD
      - POSTGRES_DB=carl
      - POSTGRES_HOST=postgres
    networks:
      - opendut_local

  carl:
    image: "ghcr.io/eclipse-opendut/opendut-carl:0.3.1"
    command: ["/opt/opendut-carl/opendut-carl"]
    restart: unless-stopped
    depends_on:
      carl_postgres:
        condition: service_healthy
      traefik:
        condition: service_started
      keycloak:
        condition: service_healthy
    volumes:
      # CUSTOM ENTRYPOINT
      - "./data/carl/entrypoint.sh:/opt/entrypoint.sh"
      - "./data/carl/carl_functions.sh:/opt/carl_functions.sh"
      # CERTIFICATES
      - "./data/secrets/pki/insecure-development-ca.pem:/etc/opendut/tls/ca.pem"
      - "./data/secrets/pki/deploy/carl.opendut.local.pem:/etc/opendut/tls/carl.pem"
      - "./data/secrets/pki/deploy/carl.opendut.local.key:/etc/opendut/tls/carl.key"
      - carl-config:/opt/opendut-carl/config/
    environment:
      # Network
      - OPENDUT_CARL_NETWORK_REMOTE_HOST=carl.opendut.local
      - OPENDUT_CARL_NETWORK_REMOTE_PORT=443
      - OPENDUT_CARL_NETWORK_BIND_PORT=443
      - OPENDUT_CARL_NETWORK_TLS_CA=/etc/opendut/tls/ca.pem
      # CURL
      - CURL_CA_BUNDLE=/etc/opendut/tls/ca.pem
      - SSL_CERT_FILE=/etc/opendut/tls/ca.pem
      # VPN
      - OPENDUT_CARL_VPN_ENABLED=true
      - OPENDUT_CARL_VPN_KIND=netbird
      - OPENDUT_CARL_VPN_NETBIRD_CA=/etc/opendut/tls/ca.pem
      - OPENDUT_CARL_VPN_NETBIRD_URL=https://netbird-api.opendut.local/api
      - OPENDUT_CARL_VPN_NETBIRD_AUTH_TYPE=personal-access-token
      # OpenTelemetry
      - OPENDUT_CARL_OPENTELEMETRY_ENABLED=false
      - OPENDUT_CARL_OPENTELEMETRY_COLLECTOR_ENDPOINT=http://otel-collector:4317
      # OIDC
      - OPENDUT_CARL_NETWORK_OIDC_ENABLED=true
      - OPENDUT_CARL_NETWORK_OIDC_CLIENT_ID=opendut-carl-client
      - OPENDUT_CARL_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_CARL_NETWORK_OIDC_LEA_ISSUER_URL=https://auth.opendut.local/realms/opendut/
      - OPENDUT_CARL_NETWORK_OIDC_CLIENT_ISSUER_URL=https://auth.opendut.local/realms/opendut/
      - OPENDUT_CARL_NETWORK_OIDC_CLIENT_ISSUER_REMOTE_URL=https://auth.opendut.local/realms/opendut/
      - OPENDUT_CARL_NETWORK_OIDC_CLIENT_ISSUER_ADMIN_URL=https://auth.opendut.local/admin/realms/opendut/
      - OPENDUT_CARL_NETWORK_OIDC_CLIENT_SCOPES=
      # Persistence
      - OPENDUT_CARL_PERSISTENCE_ENABLED=true
      - OPENDUT_CARL_PERSISTENCE_DATABASE_URL=postgres://carl_postgres/carl
      - OPENDUT_CARL_PERSISTENCE_DATABASE_USERNAME=postgres
      - OPENDUT_CARL_PERSISTENCE_DATABASE_PASSWORD=$CARL_POSTGRES_PASSWORD

      - KEYCLOAK_URL=https://auth.opendut.local/
      - NETBIRD_MANAGEMENT_URL=https://netbird-api.opendut.local
      - NETBIRD_PASSWORD
    # https://docs.docker.com/reference/dockerfile/#healthcheck
    healthcheck:
      <<: *common-healthcheck-params
      # curl --resolve carl.opendut.local:443:127.0.0.1 --fail --verbose https://carl.opendut.local
      test: ["CMD", "curl", "--resolve", "carl.opendut.local:443:127.0.0.1", "--fail", "--silent", "https://carl.opendut.local"]

    labels:
      - traefik.enable=true
      - traefik.tcp.routers.carl.rule=HostSNI(`carl.opendut.local`)
      - traefik.tcp.routers.carl.tls.passthrough=true
      - traefik.tcp.services.carl.loadbalancer.server.port=443
    networks:
      opendut_local:
        aliases:
          - carl.opendut.local

  cleo:
    build:
      context: ../../..
      dockerfile: ./.ci/deploy/localenv/data/cleo/Dockerfile
    restart: unless-stopped
    depends_on:
      carl:
        condition: service_healthy
    environment:
      # CLEO
      - OPENDUT_CLEO_NETWORK_CARL_HOST=carl.opendut.local
      - OPENDUT_CLEO_NETWORK_CARL_PORT=443
      - OPENDUT_CLEO_NETWORK_TLS_DOMAIN_NAME_OVERRIDE=carl.opendut.local  # default developer certificate is only valid for localhost
      - OPENDUT_CLEO_NETWORK_OIDC_ENABLED=true
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ID=opendut-cleo-client
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SECRET
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_ISSUER_URL=https://auth.opendut.local/realms/opendut/
      - OPENDUT_CLEO_NETWORK_OIDC_CLIENT_SCOPES=
      - OPENDUT_CLEO_NETWORK_TLS_CA=/etc/opendut/tls/ca.pem
      - SSL_CERT_FILE=/etc/opendut/tls/ca.pem
    volumes:
      - "./data/secrets/pki/insecure-development-ca.pem:/etc/opendut/tls/ca.pem"
    networks:
      - opendut_local

  nginx-webdav:
    build:
      context: ../../..
      dockerfile: ./.ci/deploy/localenv/data/nginx-webdav/Dockerfile
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
    volumes:
      - opendut_nginx-webdav:/media/data
    healthcheck:
      <<: *common-healthcheck-params
      test: ["CMD", "curl", "--resolve", "nginx-webdav.opendut.local:80:127.0.0.1", "http://nginx-webdav.opendut.local", "--output", "/dev/null"]

    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-webdav.rule=Host(`nginx-webdav.opendut.local`)
      - traefik.http.routers.nginx-webdav.tls=true
      - traefik.http.services.nginx-webdav.loadbalancer.server.port=80

    networks:
      opendut_local:
        aliases:
          - nginx-webdav.opendut.local


  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.1
    command: [ "--config.file=/etc/prometheus/prometheus.yml", "--web.enable-remote-write-receiver", "--enable-feature=exemplar-storage" ]
    restart: always
    volumes:
      - ./data/telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - opendut_local


volumes:
  keycloak_postgres_data:
  netbird-mgmt-data:
  netbird-mgmt-config:
  netbird-signal:
  carl_postgres_data:
  carl-config:
  opendut_nginx-webdav:

networks:
  opendut_local:
    name: local
    ipam:
      driver: default
      config:
        - subnet: 192.168.32.0/24
          ip_range: 192.168.32.0/24

